services:
  personen-mock:
    # from https://github.com/BRP-API/Haal-Centraal-BRP-bevragen/blob/master/docker-compose-mock.yml
    container_name: personen-mock
    image: ghcr.io/brp-api/personen-mock:2.3.0-latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5010
    networks:
      - brp-api-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "5010:80"  # Expose NGINX on port 5010
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Link to the NGINX config file
    depends_on:
      - personen-mock
    networks:
      - brp-api-network

  web:
    build:
      context: src/
      args:
        PIP_REQUIREMENTS: requirements_dev.txt
    ports:
      - "8095:8000"
    links:
      - personen-mock
    depends_on:
      - personen-mock
    environment:
      UWSGI_HTTP_SOCKET: ":8000"
      UWSGI_MODULE: "haal_centraal_proxy.wsgi"
      UWSGI_CALLABLE: "application"
      UWSGI_MASTER: 1
      UWSGI_STATIC_MAP: "/haal_centraal_proxy/static=/static"
      SECRET_KEY: insecure
      DJANGO_LOG_LEVEL: "${DJANGO_LOG_LEVEL:-INFO}"
      HAAL_CENTRAAL_BRP_URL: "http://nginx/haalcentraal/api/brp/personen"  # Update to use NGINX proxy
      LOG_LEVEL: "${LOG_LEVEL:-INFO}"
      AUDIT_LOG_LEVEL: "${AUDIT_LOG_LEVEL:-INFO}"
      AZURE_APPI_AUDIT_CONNECTION_STRING: "${AZURE_APPI_AUDIT_CONNECTION_STRING}"
      AZURE_APPI_CONNECTION_STRING: "${AZURE_APPI_CONNECTION_STRING}"
      OAUTH_CLIENT_ID: "${OAUTH_CLIENT_ID}"
      OAUTH_JWKS_URL: "${OAUTH_JWKS_URL}"
      PUB_JWKS: '{"keys":[{"kty":"EC","key_ops":["verify","sign"],"kid":"2aedafba-8170-4064-b704-ce92b7c89cc6","crv":"P-256","x":"6r8PYwqfZbq_QzoMA4tzJJsYUIIXdeyPA27qTgEJCDw=","y":"Cf2clfAfFuuCB06NMfIat9ultkMyrMQO9Hd2H7O9ZVE=","d":"N1vu0UQUp0vLfaNeM0EDbl4quvvL6m_ltjoAXXzkI3U="}]}'
      OAUTH_URL:  "${OAUTH_URL}"
      CLOUD_ENV: "${CLOUD_ENV}"
      DATAPUNT_API_URL: "${DATAPUNT_API_URL}"
      DJANGO_DEBUG: 1
    volumes:
      - ./src:/app
    command: uwsgi --py-auto-reload=1 --enable-threads --lazy-apps --buffer-size=65535
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network
